"""add_user_role_column

Revision ID: 15b34632ebca
Revises: fd34a43b37d9
Create Date: 2025-09-03 11:29:12.917924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b34632ebca'
down_revision = 'fd34a43b37d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    user_role_enum = sa.Enum('VIEWER', 'EDITOR', 'ADMIN', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('user_account', sa.Column('role', user_role_enum, nullable=False, server_default='VIEWER'))
    
    # Update existing admin user to have ADMIN role
    op.execute(sa.text("UPDATE user_account SET role = 'ADMIN' WHERE is_admin = true"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'role')
    # Drop the enum type
    user_role_enum = sa.Enum('VIEWER', 'EDITOR', 'ADMIN', name='userrole')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
